# docker compose -f docker-compose.dev.yml up -d --no-deps --build

version: '3.9'
services:
  exodus-token-refresh:
    image: dev-web-api:latest
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./Dockerfile