spring:
  profiles:
    include: secret, storage, oauth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html